In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
diamonds = pd.read_csv('./diamonds.csv')

In [11]:
diamonds

       carat        cut color clarity  depth  table  price     x     y     z
0       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
1       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
2       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
3       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
4       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
48935   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
48936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
48937   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
48938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
48939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[48940 rows x 10 columns]

In [44]:
d_mean = round(diamonds['price'].mean(),2)
d_mean

3934.41

In [45]:
rick_diamonds = pd.read_csv('./rick_diamonds.csv')

In [46]:
rick_diamonds['price_predicted'] = d_mean
rick_diamonds

,carat,cut,color,clarity,depth,table,x,y,z,price_predicted
0,0.91,Very Good,H,SI2,63.4,57.0,6.10,6.18,3.89,3934.41
1,0.38,Good,F,VS2,60.3,61.0,4.68,4.71,2.83,3934.41
2,0.52,Ideal,H,VS2,61.8,56.0,5.19,5.16,3.20,3934.41
3,1.10,Ideal,G,VS1,61.3,56.0,6.65,6.69,4.09,3934.41
4,2.28,Ideal,G,SI2,61.6,57.0,8.44,8.37,5.18,3934.41
...,...,...,...,...,...,...,...,...,...,...
4995,0.30,Very Good,D,SI2,62.2,59.0,4.25,4.30,2.66,3934.41
4996,0.51,Ideal,F,VVS2,61.9,56.0,5.09,5.14,3.16,3934.41
4997,1.01,Very Good,F,SI1,60.6,60.0,6.37,6.43,3.88,3934.41
4998,0.31,Ideal,F,VVS1,62.1,56.0,4.35,4.38,2.71,3934.41
4999,0.33,Ideal,E,VS2,61.8,55.0,4.45,4.48,2.76,3934.41

In [47]:
diamonds['price_predicted'] = d_mean

In [48]:
from sklearn.metrics import r2_score

r2 = r2_score(diamonds['price'], diamonds['price_predicted'])

print(f'r2 = {r2}')

r2 = -7.993605777301127e-15

In [49]:
from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(diamonds['price'], diamonds['price_predicted']))

print(f'Root mean squared error = {rmse}')

Root mean squared error = 3989.293102899167

In [50]:
rick_diamonds.to_csv('./rick_diamonds_2.csv')